import { options } from 'toastr';

export const toastrOptions: typeof options = {
  closeButton: true,
  newestOnTop: false,
  progressBar: true,
  preventDuplicates: true,
  showDuration: 300,
  hideDuration: 1000,
  timeOut: 2000,
  extendedTimeOut: 1000,
  showEasing: 'swing',
  hideEasing: 'linear',
  showMethod: 'fadeIn',
  hideMethod: 'fadeOut',
  positionClass: 'toast-bottom-left',
};

export const currencyAssotiations = {
  '1': '$',
  '2': '£',
  '3': '€',
  '4': 'CHF',
  '5': '₽',
  '6': 'zł',
  '7': 'R$',
  '8': '¥',
  '9': 'kr',
  '10': 'Rp',
  '11': 'RM',
  '12': 'P',
  '13': 'S$',
  '14': '฿',
  '15': '₫',
  '16': '₩',
  '17': 'TL',
  '18': '₴',
  '19': 'Mex$',
  '20': 'CDN$',
  '21': 'A$',
  '22': 'NZ$',
  '23': '¥',
  '24': '₹',
  '25': 'CLP$',
  '26': 'S/.',
  '27': 'COL$',
  '28': 'R',
  '29': 'HK$',
  '30': 'NT$',
  '31': 'SR',
  '32': 'AED',
  '34': 'ARS$',
  '35': '₪',
  '36': 'Br',
  '37': '₸',
  '38': 'KD',
  '39': 'QR',
  '40': '₡',
  '41': '$U',
} as const;
